### ISSUE TITLE
`__UnpinStruct`  is restricting the pinned field.

### ISSUE THREAD

**Issue by ogoffart** [taiki-e/pin-project#102]
Unless I misunderstand something, it seems the logic to put the field in __UnpinStruct is reversed, as it checks that the #[pin]'ed field are Unpin.

For example:

```
// This structure cannot be moved
struct Property {
    pin: std::marker::PhantomPinned
}

#[pin_project::pin_project]
struct Container {
    #[pin]
    xxx : Property
}
```

Result in this error:

```
error[E0277]: the trait bound `std::marker::PhantomPinned: std::marker::Unpin` is not satisfied in `__unpin_scope_Container::__UnpinStructContainer`
   |
20 | #[pin_project::pin_project]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ within `__unpin_scope_Container::__UnpinStructContainer`, the trait `std::marker::Unpin` is not implemented for `std::marker::PhantomPinned`
   |
```

__UnpinStruct constraints all the pin'ed types. But I believe it should be the opposite, only the types that are not pinned should satisfy Unpin.

**Comment by Aaron1011** [comment]
This logic is current. `__UnpinStruct: Unpon` is used as a bound for the pin-projected strict. That is, you can only treat pin projections as `Unpin` when all of the pinned types are also `Unpin` (I.e. when IRS safe to ignore the fact that they are pinned).

**Comment by taiki-e** [comment]
This error is because the `Unpin` implementation provided by `pin_project` adds a `Unpin` bound to a field that is known not to implement `Unpin` (It doesn't matter if it is explicit). This can be resolved if [RFC 2056](https://github.com/rust-lang/rfcs/blob/master/text/2056-allow-trivial-where-clause-constraints.md) (https://github.com/rust-lang/rust/issues/48214) stabilizes. 

The workaround I know is using `pin_project(UnsafeUnpin)` and not providing a manual `UnsafeUnpin` implementation.
https://github.com/taiki-e/pin-project/blob/1b0e5526e8c0eb99867272533d6cd81902418acd/src/lib.rs#L93-L95

However, perhaps we can provide an option to support this. (Add the `PhantomPinned` argument to `pin_project` or parse the field to automatically adjust the `Unpin` implementation. Personally I prefer to pass arguments explicitly.)

(FYI: I found this problem about two weeks ago and added two tests.)
* [pin-project/tests/ui/pin_project/trivial_bounds.rs](https://github.com/taiki-e/pin-project/blob/1b0e5526e8c0eb99867272533d6cd81902418acd/tests/ui/pin_project/phantom-pinned.rs)
  https://github.com/taiki-e/pin-project/blob/1b0e5526e8c0eb99867272533d6cd81902418acd/tests/ui/pin_project/phantom-pinned.stderr#L1-L16

* [pin-project/tests/ui/pin_project/trivial_bounds.rs](https://github.com/taiki-e/pin-project/blob/1b0e5526e8c0eb99867272533d6cd81902418acd/tests/ui/pin_project/trivial_bounds.rs)

**Comment by ogoffart** [comment]
Actually, the full error message tells that the problem is  because of https://github.com/rust-lang/rust/issues/48214

This reduce the utility of this macro if it can only be done for generic types.

Maybe the pin_project macro should add a `<T = ()>`

**Comment by taiki-e** [comment]
@ogoffart
> Maybe the pin_project macro should add a `<T = ()>`

I'm not sure about how does this resolve the problem - Could you explain in a little more detail?

**Comment by ogoffart** [comment]
Because having a generic in the structure work around the issue 48214.
But i actually think pin_project should not add that, because it would also then add a field which we don't want.

I don't understand how to use `pin_project(UnsafeUnpin)` to work this around.  It just change the error to 

```
error[E0277]: the trait bound `Container: pin_project::UnsafeUnpin` is not satisfied
```

**Comment by taiki-e** [comment]
> I don't understand how to use `pin_project(UnsafeUnpin)` to work this around. It just change the error to

Oops, sorry, my comment is wrong. It doesn't work.

**Comment by taiki-e** [comment]
Hmm... I'm not sure how to support this without unstable features (I think it needs `trivial_bounds` or `optin_builtin_traits`).

cc @cramertj @RalfJung @Nemo157 Do you know a workaround for this?

**Comment by taiki-e** [comment]
We can partially support this if we use [the same way that we prohibit manual implementation of `Drop`](https://github.com/taiki-e/pin-project/pull/48), but it doesn't work well with struct that has generics. 

```rust
struct Inner(PhantomPinned);

// #[pin_project(!Unpin)]
struct Foo {
    // #[pin]
    pinned: Inner,
}

impl Unpin for Foo {} //~ ERROR conflicting implementations of trait `test::MustNotImplUnpin` for type `test::Foo`:

// pin_project generates the following code.
trait MustNotImplUnpin {}
impl<T: Unpin> MustNotImplUnpin for T {}
impl MustNotImplUnpin for Foo {}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=82c28b5183d154f788ad3d0a499ea2c4)

(Replacing generics with `()` on `impl MustNotImplUnpin` will probably resolve some problems, but it won't work for generics with trait bounds.)

**Comment by ogoffart** [comment]
@taiki-e   your `MustNotImplUnpin` does not seem to work.  I get the compilation error even if i comment the `impl Unpin`

**Comment by taiki-e** [comment]
Oh... you are right.

**Comment by taiki-e** [comment]
This worked well in 0.3, so I think it should actually be considered a regression.

**Comment by taiki-e** [comment]
Perhaps a realistic solution would be to add a new `#[unsafe_project]` that removes the guarantee about Unpin from `#[pin_project]`.  The document probably has the following wording: "Safety: This macro is safe unless you manually add an Unpin implementation."  and "This macro is basically deprecated. Should not be used except in use cases like #102."

@Aaron1011 Any thoughts?

**Comment by ogoffart** [comment]
How about `#[pin_project(unsafe)]`   so the unsafe keyword appears literally in the source.

But yes, the documentation should maybe recommend the trick to add a (useless) generic parameter so it compiles.

```
#[pin_project::pin_project]
struct Container<T = ()> {
    #[pin]
    xxx : Property,
    phantom: PhantomData<T>,
}
```

It also work with a generic lifetime :+1: 

```
#[pin_project::pin_project]
struct Container<'a> {
    #[pin]
    xxx : Property,
    phantom: PhantomData<&'a u32>,
}
```

And the compilation error can be hinting about this. The macro can detect that there is no generic argument and have its own error, or rename the field `__UnpinStructContainer`  to `__UnpinStructContainer_CheckIssue_xxx` or

**Comment by taiki-e** [comment]
> How about `#[pin_project(unsafe)]` so the unsafe keyword appears literally in the source.

Can `#[warn(unsafe_core)]` or `cargo geiger` detect this?

> But yes, the documentation should maybe recommend the trick to add a (useless) generic parameter so it compiles.

I don't think the problem is related to generics.
`Unpin` implementation provided by pin-project adds Unpin bounds for all fields (it does not matter whether fields are generics or not) annotated with `#[pin]` .
The problem is that if this includes a type that compiler know doesn't implement `Unpin`, you get an error.

**Comment by taiki-e** [comment]
For clarity: 
The major goal of 0.4 is to prevent you from writing unsound code unless you use `unsafe` code.
The problem is that the method we use to guarantee this introduces a limitation. 
(*Note: It is not safe to implement Unpin when using pin projection*). 
Currently, the stable version of rustc cannot use the negative trait implementation, so if you want to ban to implement `Unpin` without `unsafe`, pin-project needs to implement `Unpin` in some way.
This will not work if `Unpin` cannot be implemented like this case. But, if pin-project does not implement `Unpin`, the user can write an unsound `Unpin` implementation without `unsafe`.
(If `Unpin` is an unsafe trait, these will not be a problem...)

**Comment by ogoffart** [comment]
> Can #[warn(unsafe_core)] or cargo geiger detect this?

Depends what code the macro generates. But if you use the Span from the unsafe keyword, it will be reported as a waring/error there.

> I don't think the problem is related to generics.

It is a problem related to not having generic.  (rust issue 48214)

If the struct have generics, everything works fine.

**Comment by taiki-e** [comment]
> It is a problem related to not having generic. (rust issue 48214)
> 
> If the struct have generics, everything works fine.

Oh, you are right, I confirmed locally.  I didn't understand about this feature properly... sorry.

> Depends what code the macro generates. But if you use the Span from the unsafe keyword, it will be reported as a waring/error there.
> 

This seems to work well, thanks. (If this is actually adopted, it seems necessary to propagate `allow(unsafe)` correctly)

**Comment by taiki-e** [comment]
(In fact, many of my comments on this issue seem wrong... sorry for that.)

**Comment by taiki-e** [comment]
@ogoffart 

Perhaps the minimal fix to this issue is to mention errors and workarounds in the documentation? (https://github.com/taiki-e/pin-project/issues/102#issuecomment-534243988)

And do we also need to provide a way to completely disable the pin-project unpin guarantee to improve ergonomics? (https://github.com/taiki-e/pin-project/issues/102#issuecomment-534226026)

**Comment by taiki-e** [comment]
> The workaround I know is using pin_project(UnsafeUnpin) and not providing a manual UnsafeUnpin implementation.

> I don't understand how to use `pin_project(UnsafeUnpin)` to work this around. It just change the error to

I think I found a way to fix this: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e890c6d3ab856254367283ae8b744778)

**Comment by taiki-e** [comment]
Filed #107

**Comment by ogoffart** [comment]
Nice!

I also found another way to error out if Unpin is implemented
I'll let you decide which one you prefer.

```
    #![allow(dead_code)]
    use core::marker::{PhantomPinned};

    mod pin_project {
    pub trait ThouShalltNotImlementUnpin {
        fn test(&self) {}
    }
    impl<T : Unpin> ThouShalltNotImlementUnpin for T {}
    
    pub trait Xx {
        fn test(&self) {}
    }
    
    impl<T> Xx for T {}
    }


    struct Foo {
        // #[pin]
        x: PhantomPinned,
    }
  
    fn test(f : &Foo) {
        #[allow(unused_imports)]
        use pin_project::ThouShalltNotImlementUnpin;
        use pin_project::Xx;
        f.test();
    }
    
    //impl Unpin for Foo {}    // this would error
    ```

**Comment by jonhoo** [comment]
I wonder if https://docs.rs/static_assertions/0.3/static_assertions/macro.assert_not_impl_any.html might be something to look into.

**Comment by taiki-e** [comment]
@ogoffart
Thanks, #107 is a fix for a known workaround that doesn't work properly, and https://github.com/taiki-e/pin-project/issues/102#issuecomment-534995349 is a technique needed to improve the API that I mentioned in https://github.com/taiki-e/pin-project/issues/102#issuecomment-533817011, so I think they don't overlap :)
However, [that way seems can be broken the guarantee by adding a method `test` to Foo.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cd3266a7d06bd8e3c288564cf668c39d)

@jonhoo 
Thanks. [That way doesn't seem to work well with generics.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=963a87c412f6fde93e63704b636153b5)

**Comment by taiki-e** [comment]
Unfortunately, it seems difficult to guarantee negative implementations at this time (but thanks for the info @ogoffart and @jonhoo!)

**Comment by taiki-e** [comment]
I've filed #108 to investigate how to guarantee negative implementation.

**Comment by ogoffart** [comment]
> However, that way seems can be broken the guarantee by adding a method test to Foo.

Good catch!
We can fix that by having the test function return a sealed type
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d1a2fea5630d880cd04a7cb1f1f1f797

**Comment by taiki-e** [comment]
> We can fix that by having the test function return a sealed type

Cool! But it still doesn't seem to work well with generics and conditional implementations.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=57d4003292043b28b52f07709ed0c893

**Comment by taiki-e** [comment]
By the way, it seems `#[pin_project]` (not `UnsafeUnpin`) can support this in the same way I used in #107 :)

If we can support this without `UnsafeUnpin`, I don't think we need negative implementation support either.

**Comment by taiki-e** [comment]
Published 0.4.1 which fixes this issue completely. `#[pin_project]` can now support this without `UnsafeUnpin`.

**Comment by RalfJung** [comment]
Reading this thread here I am mostly left confused. Given all the corrections I do not seem to be the only one. ;)

Is there a write-up somewhere of the solution you ended up with, how it works and what it relies on from rustc?

**Comment by RalfJung** [comment]
Okay, so it's basically a weird hack to hack around a weird rule in the trait system. Thanks.

The number of hacks that keep piling up in this crate is quite impressive... and worrying.
