### ISSUE TITLE
Regression: cannot return value referencing function parameter `self`

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/pin-project#65]
Caused by #47.

[Such code is used a lot in futures etc.](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/stream/buffered.rs#L79), so I would like to support it...
However, I'm not sure if this can be fixed by ways other than changing `self` argument to `self: Pin<&mut Self>`.

Code: 
```rust
use std::pin::Pin;

#[pin_project::pin_project]
struct Struct<T, U> {
    #[pin]
    pinned: T,
    unpinned: U,
}

impl<T, U> Struct<T, U> {
    fn get_pin_mut<'a>(mut self: Pin<&'a mut Self>) -> Pin<&'a mut T> {
        self.project().pinned
    }
}
```

Error:
```text
error[E0515]: cannot return value referencing function parameter `self`
  --> src/lib.rs:33:9
   |
33 |         self.project().pinned
   |         ----^^^^^^^^^^^^^^^^^
   |         |
   |         returns a value referencing data owned by the current function
   |         `self` is borrowed here
```

[playground (current)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdc59f2814cd6fb62a857c69cf34b16b)

[playground (previous)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdc59f2814cd6fb62a857c69cf34b16b)

**Comment by taiki-e** [comment]
cc @Aaron1011

**Comment by taiki-e** [comment]
By the way, [even if arbitrary_self_types is used, this seems to be an error.](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8070a52e8a37dd07e6fe076efba82a0a)

**Comment by Aaron1011** [comment]
I've found a solution - I'll be opening a PR soon.
