### PR TITLE
Add 'project_into' method to #[pin_project] types

### LINKED ISSUE #65: Regression: cannot return value referencing function parameter `self`
Caused by #47.

[Such code is used a lot in futures etc.](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-util/src/stream/buffered.rs#L79), so I would like to support it...
However, I'm not sure if this can be fixed by ways other than changing `self` argument to `self: Pin<&mut Self>`.

Code: 
```rust
use std::pin::Pin;

#[pin_project::pin_project]
struct Struct<T, U> {
    #[pin]
    pinned: T,
    unpinned: U,
}

impl<T, U> Struct<T, U> {
    fn get_pin_mut<'a>(mut self: Pin<&'a mut Self>) -> Pin<&'a mut T> {
        self.project().pinned
    }
}
```

Error:
```text
error[E0515]: cannot return value referencing function parameter `self`
  --> src/lib.rs:33:9
   |
33 |         self.project().pinned
   |         ----^^^^^^^^^^^^^^^^^
   |         |
   |         returns a value referencing data owned by the current function
   |         `self` is borrowed here
```

[playground (current)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdc59f2814cd6fb62a857c69cf34b16b)

[playground (previous)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdc59f2814cd6fb62a857c69cf34b16b)

### PR DESCRIPTION
**Pull request by Aaron1011**
This method consumes takes a 'Pin<&mut Self>' by value, instead
of by mutable reference. This allows us to give the projection
struct/enum a longer lifetime, which is required when returning it
from a function

Fixes #65

### CODE REVIEW

**Comment by taiki-e** [comment]
I was thinking of changing the argument type back to `self: Pin<&mut Self>` (8735be852b9a8fe27fd29c9f77eb2bb5b44b0fe7), but this seems to be fine considering that there are probably not many use cases like #65.

**Comment by taiki-e** [comment]
@Aaron1011 Thanks for all of your work on this!

bors r+

File: pin-project-internal/src/lib.rs [hunk 1]
```diff
@@ -31,6 +31,32 @@ use syn::parse::Nothing;
 /// the field.
 /// - For the other fields, makes the unpinned reference to the field.
 ///
+/// The following methods are implemented on the original `#[pin_project]` type:
+///
+/// ```ignore
+/// fn project(&mut Pin<&mut Self>) -> ProjectedType;
+/// fn project_into(Pin<&mut Self>) -> ProjectedType;
```
Comment (RalfJung) [inline pin-project-internal/src/lib.rs]: I think `project` should take `Pin<&mut Self>`, the double ptr-indirection looks very strange. The argument for why it has been added is incorrect I think, see what I wrote at https://github.com/taiki-e/pin-project/pull/47#issuecomment-530467225.
